#!/bin/bash
# Script to retrieve GCP recommendation details from all projects.
# Author - Rajathithan Rajasekar - 07/20/2021

echo "PROJECT-NAME, RECOMMENDATION-PRIORITY , RECOMMENDATION-TYPE , MACHINE-NAME , ZONE , CURRENT-MACHINE-TYPE , RECOMMENDED-MACHINE-TYPE, TOTAL-COST-SAVINGS-IN-USD" > gcp-recommendations.csv
prjs=( $(gcloud projects list | tail -n +2 | awk {'print $1'}) )
token=$(gcloud auth print-access-token)
for i in "${prjs[@]}"
    do
        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" 
        echo "Setting Project: $i" 
        echo $(gcloud config set project $i )
        echo $(gcloud services enable recommender.googleapis.com)
        #echo $(gcloud auth application-default set-quota-project $i)
        echo $(gcloud projects list --filter=$i --format='value(PROJECT_NUMBER)' | while read line; do echo "$i $line $token"; done | xargs -n3 sh -c 'python3 retrieve-recommendations.py $1 $2 $3 >> gcp-recommendations.csv' sh)
    done
